### ISSUE TITLE
InCommon Satosa Configuration

### ISSUE THREAD

**Issue by bboggmsu** [MESH-Research/commons-idms#10]
- [ ] Create a running SATOSA container using Docker.

- [ ] Mirror the basic current setup on the new SATOSA container.

- [ ] Compare the new vs. current setup.
